apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      name: tic-tac-toe
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe-server
          image: tic-tac-toe-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: api
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: api
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 12
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: api
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 5m
              memory: 250Mi
          env:
            - name: MCTS_MAX_DESCENDANT_LEVEL
              value: "2"
            - name: MOVE_FUNCTION_URL
              value: "https://europe-west1-decent-micron-196515.cloudfunctions.net/tic-tac-toe-move"
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
      restartPolicy: Always
      volumes:
        - name: google-cloud-key
          secret:
            secretName: tic-tac-toe-sa-key