apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      name: tic-tac-toe
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe-server
          image: tic-tac-toe-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: api
          readinessProbe:
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 12
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: MCTS_NAIVE_GAMES_PER_ROLLOUT
              value: "20"
            - name: MCTS_RANDOM_ADJACENT_GAMES_PER_ROLLOUT
              value: "80"
            - name: MCTS_UNIFORM_RANDOM_GAMES_PER_ROLLOUT
              value: "280"
      restartPolicy: Always
      